In [3]:
import pandas as pd

In [20]:
filepath1 = "Cocktail-Creator/Data/statelatlong.csv"

state_df = pd.read_csv(filepath1)


state_df.head()

  abbr   latitude   longitude       state
0   AL  32.601011  -86.680736     Alabama
1   AK  61.302501 -158.775020      Alaska
2   AZ  34.168219 -111.930907     Arizona
3   AR  34.751928  -92.131378    Arkansas
4   CA  37.271875 -119.270415  California

In [23]:
filepath2 = "Cocktail-Creator/Data/state_cocktail.csv"

cocktail_df = pd.read_csv(filepath2)

cocktail_df.head()

        state          cocktail
0     Alabama         Hurricane
1      Alaska      Whiskey Sour
2     Arizona            Paloma
3    Arkansas   Frozen Daiquiri
4  California            Paloma

In [24]:
combined_df = pd.merge(state_df, cocktail_df, on="state")

combined_df

   abbr   latitude   longitude                 state             cocktail
0    AL  32.601011  -86.680736               Alabama            Hurricane
1    AK  61.302501 -158.775020                Alaska         Whiskey Sour
2    AZ  34.168219 -111.930907               Arizona               Paloma
3    AR  34.751928  -92.131378              Arkansas      Frozen Daiquiri
4    CA  37.271875 -119.270415            California               Paloma
5    CO  38.997934 -105.550567              Colorado            Hurricane
6    CT  41.518784  -72.757507           Connecticut            Margarita
7    DE  39.145251  -75.418921              Delaware          Screwdriver
8    DC  38.899349  -77.014567  District of Columbia       Old Fashioned
9    FL  27.975728  -83.833017               Florida           Cuba Libre
10   GA  32.678125  -83.222976               Georgia              Sazerac
11   HI  20.460000 -157.505000                Hawaii   Lemon Drop Martini
12   ID  45.494576 -114.142430                 Idaho             Kamikaze
13   IL  39.739318  -89.504139              Illinois            Manhattan
14   IN  39.766219  -86.441277               Indiana            French 75
15   IA  41.938317  -93.389798                  Iowa             Kamikaze
16   KS  38.498779  -98.320078                Kansas          Screwdriver
17   KY  37.822294  -85.768240              Kentucky                 Lily
18   LA  30.973377  -91.429910             Louisiana           Bushwacker
19   ME  45.218513  -69.014866                 Maine            Margarita
20   MD  38.806352  -77.268416              Maryland             Kamikaze
21   MA  42.062940  -71.718067         Massachusetts        Old Fashioned
22   MI  44.943560  -86.415805              Michigan                Cosmo
23   MN  46.441859  -93.365515             Minnesota             Oliveto
24   MS  32.585106  -89.877220           Mississippi           Painkiller
25   MO  38.304662  -92.437099              Missouri       Gin and Tonic
26   MT  46.679800 -110.044783               Montana       Blue Hawaiian
27   NE  41.500819  -99.680902              Nebraska        Old Fashioned
28   NV  38.502032 -117.023060                Nevada          Grasshopper
29   NH  44.001231  -71.579923         New Hampshire        Old Fashioned
30   NJ  40.143006  -74.731116            New Jersey            Manhattan
31   NM  34.166232 -106.026069            New Mexico        Old Fashioned
32   NY  40.705626  -73.979680              New York            Manhattan
33   NC  35.214563  -79.891267        North Carolina           Bushwacker
34   ND  47.467882 -100.302266          North Dakota             Kamikaze
35   OH  40.190362  -82.669252                  Ohio         Boulevardier
36   OK  35.309765  -98.716558              Oklahoma        Black Russian
37   OR  44.141905 -120.538099                Oregon        Old Fashioned
38   PA  40.994593  -77.604698          Pennsylvania        Whiskey Sour
39   RI  41.582728  -71.506451          Rhode Island               Cosmo
40   SC  33.625050  -80.947038        South Carolina      Tequila Sunrise
41   SD  44.212699 -100.247164          South Dakota          Screwdriver
42   TN  35.830521  -85.978599             Tennessee          Buschwacker
43   TX  31.169336 -100.076842                 Texas               Paloma
44   UT  39.499761 -111.547028                  Utah             Cape Cod
45   VT  43.871755  -72.447783               Vermont         Cosmopolitan
46   VA  38.003386  -79.458786              Virginia        Old Fashioned
47   WA  38.899349  -77.014567            Washington        Old Fashioned
48   WV  38.920171  -80.181691         West Virginia             Kamikaze
49   WI  44.786297  -89.826705             Wisconsin          Grasshopper
50   WY  43.000325 -107.554567               Wyoming        White Russian

In [25]:
combined_df.to_csv("Cocktail-Creator/Data/combined_state.csv", encoding="utf-8", index=False, header=True)